"""Phase 3 : ventes, vente_lignes, pertes, stocks_journaliers

Revision ID: 0c8886c4b2db
Revises: 4e7e3e1c2969
Create Date: 2026-07-02 12:46:34.263707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8886c4b2db'
down_revision = '4e7e3e1c2969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks_journaliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('boutique_id', sa.Integer(), nullable=False),
    sa.Column('date_stock', sa.Date(), nullable=False),
    sa.Column('stock_initial', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('entrees', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('sorties', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('pertes', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('stock_final', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('stock_physique', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ecart', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('boutique_id', 'produit_id', 'date_stock', name='uq_stock_btq_produit_date')
    )
    with op.batch_alter_table('stocks_journaliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocks_journaliers_date_stock'), ['date_stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocks_journaliers_produit_id'), ['produit_id'], unique=False)

    op.create_table('pertes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('boutique_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('motif', sa.String(length=200), nullable=False),
    sa.Column('valeur_perte', sa.Integer(), nullable=False),
    sa.Column('date_perte', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pertes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pertes_date_perte'), ['date_perte'], unique=False)
        batch_op.create_index(batch_op.f('ix_pertes_produit_id'), ['produit_id'], unique=False)

    op.create_table('ventes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_ticket', sa.String(length=20), nullable=False),
    sa.Column('date_vente', sa.Date(), nullable=False),
    sa.Column('heure_vente', sa.Time(), nullable=False),
    sa.Column('mode_paiement', sa.Enum('especes', 'mtn_momo', 'moov_money', 'celtiis', name='mode_paiement_enum'), nullable=False),
    sa.Column('montant_total', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('valide', 'annule', name='statut_vente_enum'), nullable=False),
    sa.Column('boutique_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_ticket')
    )
    with op.batch_alter_table('ventes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ventes_date_vente'), ['date_vente'], unique=False)

    op.create_table('vente_lignes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vente_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('prix_catalogue', sa.Integer(), nullable=False),
    sa.Column('prix_applique', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('cmup_au_moment', sa.Integer(), nullable=False),
    sa.Column('marge', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.ForeignKeyConstraint(['vente_id'], ['ventes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vente_lignes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vente_lignes_produit_id'), ['produit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vente_lignes_vente_id'), ['vente_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vente_lignes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vente_lignes_vente_id'))
        batch_op.drop_index(batch_op.f('ix_vente_lignes_produit_id'))

    op.drop_table('vente_lignes')
    with op.batch_alter_table('ventes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ventes_date_vente'))

    op.drop_table('ventes')
    with op.batch_alter_table('pertes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pertes_produit_id'))
        batch_op.drop_index(batch_op.f('ix_pertes_date_perte'))

    op.drop_table('pertes')
    with op.batch_alter_table('stocks_journaliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_journaliers_produit_id'))
        batch_op.drop_index(batch_op.f('ix_stocks_journaliers_date_stock'))

    op.drop_table('stocks_journaliers')
    # ### end Alembic commands ###
