"""Ajoute DemandeAcces (formulaire landing page)

Revision ID: 3fe87d8f1c90
Revises: bc6e37f91b70
Create Date: 2026-07-13 22:29:12.796206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe87d8f1c90'
down_revision = 'bc6e37f91b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demandes_acces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_poissonnerie', sa.String(length=150), nullable=False),
    sa.Column('responsable', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nombre_boutiques', sa.Integer(), nullable=False),
    sa.Column('traite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demandes_acces')
    # ### end Alembic commands ###
