"""Phase 2 : produits, prix_historique, achats

Revision ID: 4e7e3e1c2969
Revises: 3863e503afd1
Create Date: 2026-07-02 09:04:43.875113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7e3e1c2969'
down_revision = '3863e503afd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('categorie', sa.Enum('poisson', 'viande', name='categorie_enum'), nullable=False),
    sa.Column('unite', sa.Enum('kg', 'piece', name='unite_enum'), nullable=False),
    sa.Column('prix_achat', sa.Integer(), nullable=False),
    sa.Column('prix_vente', sa.Integer(), nullable=False),
    sa.Column('cmup_actuel', sa.Integer(), nullable=False),
    sa.Column('seuil_alerte', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produits_nom'), ['nom'], unique=True)

    op.create_table('achats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('boutique_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('prix_unitaire', sa.Integer(), nullable=False),
    sa.Column('montant_total', sa.Integer(), nullable=False),
    sa.Column('cmup_apres', sa.Integer(), nullable=False),
    sa.Column('fournisseur', sa.String(length=100), nullable=True),
    sa.Column('date_achat', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achats_date_achat'), ['date_achat'], unique=False)
        batch_op.create_index(batch_op.f('ix_achats_produit_id'), ['produit_id'], unique=False)

    op.create_table('prix_historique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('type_prix', sa.Enum('achat', 'vente', name='type_prix_enum'), nullable=False),
    sa.Column('ancien_prix', sa.Integer(), nullable=False),
    sa.Column('nouveau_prix', sa.Integer(), nullable=False),
    sa.Column('date_effet', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prix_historique', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prix_historique_produit_id'), ['produit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prix_historique', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prix_historique_produit_id'))

    op.drop_table('prix_historique')
    with op.batch_alter_table('achats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achats_produit_id'))
        batch_op.drop_index(batch_op.f('ix_achats_date_achat'))

    op.drop_table('achats')
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produits_nom'))

    op.drop_table('produits')
    # ### end Alembic commands ###
