"""ajoute uuid_client sur ventes (sync hors-ligne)

Revision ID: a9a5f9e45d5d
Revises: 3fe87d8f1c90
Create Date: 2026-07-26 10:56:33.022753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a5f9e45d5d'
down_revision = '3fe87d8f1c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid_client', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_ventes_uuid_client'), ['uuid_client'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ventes_uuid_client'))
        batch_op.drop_column('uuid_client')

    # ### end Alembic commands ###
