"""Phase 4 : clotures, reouvertures, audit_log

Revision ID: be7908de3f57
Revises: 0c8886c4b2db
Create Date: 2026-07-02 13:04:54.980017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7908de3f57'
down_revision = '0c8886c4b2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', name='action_enum'), nullable=False),
    sa.Column('table_nom', sa.String(length=50), nullable=False),
    sa.Column('enregistrement_id', sa.Integer(), nullable=False),
    sa.Column('ancienne_valeur', sa.Text(), nullable=True),
    sa.Column('nouvelle_valeur', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_table_nom'), ['table_nom'], unique=False)

    op.create_table('clotures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_periode', sa.Enum('jour', 'semaine', 'mois', name='type_periode_enum'), nullable=False),
    sa.Column('periode_debut', sa.Date(), nullable=False),
    sa.Column('periode_fin', sa.Date(), nullable=False),
    sa.Column('statut', sa.Enum('cloture', 'rouvert', name='statut_cloture_enum'), nullable=False),
    sa.Column('sans_activite', sa.Boolean(), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('boutique_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('boutique_id', 'type_periode', 'periode_debut', 'periode_fin', name='uq_cloture_btq_periode')
    )
    with op.batch_alter_table('clotures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clotures_periode_debut'), ['periode_debut'], unique=False)
        batch_op.create_index(batch_op.f('ix_clotures_periode_fin'), ['periode_fin'], unique=False)

    op.create_table('reouvertures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cloture_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cloture_id'], ['clotures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reouvertures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reouvertures_cloture_id'), ['cloture_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reouvertures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reouvertures_cloture_id'))

    op.drop_table('reouvertures')
    with op.batch_alter_table('clotures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clotures_periode_fin'))
        batch_op.drop_index(batch_op.f('ix_clotures_periode_debut'))

    op.drop_table('clotures')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_table_nom'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
